name: CI/CD Pipeline
on:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3 
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.3'
          
      - name: Install dependencies
        run: go mod download
          
      - name: Run tests
        run: go test

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - uses: actions/checkout@v3 
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/healthcheck_prueba
          tags: |
            type=sha,prefix=
            type=ref,event=branch
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
  
    environment:
      name: production
      url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to production
        run: |
          echo "Desplegando aplicación..."
          echo "URL de despliegue: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
